[config]
skip_core_tasks = true

[tasks.fmt]
command = 'cargo'
args = ["fmt"]

[tasks.build]
script = '''
wasm-pack build --target nodejs --scope dr666m1
cp ./LICENSE* pkg/
'''

[tasks.test]
script = '''
cargo fmt --check
cargo test
wasm-pack test --node
'''

[tasks.publish]
command = 'npm'
args = ['publish', '--access', 'public']
cwd = './pkg'
dependencies = ["build"]
