on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        key: ${{ hashFiles('./Cargo.lock') }}
        # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/db

    - run: command -v wasm-pack || cargo install wasm-pack
    - run: command -v makers || cargo install cargo-make

    - run: makers test

    - uses: actions/setup-node@v3
      if: ${{ github.ref_type == 'tag' }}
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - run: make rs publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

